In [1]:
import numpy as np

In [2]:
# Assuming X is your input array of length 32
X = np.random.randint(low = 1, high = 10, size = (1000, 32))  # Example input, replace it with your actual array, 
X.shape
print(X)

[[1 3 8 ... 5 1 2]
 [9 3 2 ... 1 5 8]
 [4 9 9 ... 7 9 3]
 ...
 [6 5 3 ... 7 2 8]
 [9 8 7 ... 6 6 5]
 [5 2 6 ... 2 1 9]]


In [3]:
# Get the indices for the upper triangle, avoiding the diagonal
i, j = np.triu_indices(len(X[1, ]), k=1)
len(i)

496

In [4]:
# Calculate the pairwise products
pairwise_products = X[:, i] * X[:, j]
pairwise_products

array([[ 3,  8,  6, ...,  5, 10,  2],
       [27, 18, 72, ...,  5,  8, 40],
       [36, 36, 36, ..., 63, 21, 27],
       ...,
       [30, 18, 36, ..., 14, 56, 16],
       [72, 63,  9, ..., 36, 30, 30],
       [10, 30, 45, ...,  2, 18,  9]])

In [5]:
# Concatenate the original X with the pairwise products
phi = np.append(X, pairwise_products, axis = 1)

In [6]:
phi.shape

(1000, 528)

In [ ]:
X